[package]
name = "japanoil-scraper"
version = "0.1.0"
edition = "2021"

[rustfmt]
max_width = 80

[dependencies]
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.22.0"
once_cell = "1.17.1"
csv = "1.3.1"
